### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by DrProf1** [Rednick16/libSupport#3]
My game crashes every single time i hit thanks even though i put in everything you said to me

**Comment by DrProf1** [comment]
İt says the deb is malformed

**Comment by Rednick16** [comment]
You can’t directly use my deb yet you have to compile it yourself or use semi auto version I made

https://iosgods.com/topic/162808-auto-jailed_support-sideload-detection-bypass-all-appsgames/#comment-5203953

**Comment by Rednick16** [comment]
Okay since there is nothing else closing for now
