### ISSUE TITLE
Undefined Symbols 

### ISSUE THREAD

**Issue by CarsonARK** [Rednick16/libSupport#5]
When typing "make package" in theos, it returns many undefined symbols errors. I tried removing .Theos and removing the $(LIBRARY_NAME)_INSTALL_PATH = @executable_path/Frameworks as sugguested in another comment, however it did not work. 
Undefined symbols for architecture arm64:
  "_objc_msgSend$UTF8String", referenced from:
      l005 in libsupport.a(dyld.m.0e83968f.o)
      _SupportGetDyldImageName in libsupport.a(dyld.m.0e83968f.o)

**Comment by Rednick16** [comment]
on which platform are you using theos?

**Comment by Rednick16** [comment]
hopefully libSupport 1.2.1 will fix the linking issues it should work for mobile theos as well btw
