### ISSUE TITLE
如何 hook sub_xxxx 函数

### ISSUE THREAD

**Issue by fly0903** [Rednick16/libSupport#6]

**Comment by Rednick16** [comment]
Reopening this atm because (hooking & code patching) sub_xxx on non jailbroken devices is now possible with JIT (Just-In-Time)
* an update is on the way libSupport (1.2.1)

**Comment by Rednick16** [comment]
hooking sub_x is now possible libSupport 1.2.1 (you can use JIT, Xcode debugger), or check the flags for the hooking function and use `SupportHookTypeE` for the type
